defaultProject: gds-social-data
defaultDataset: dataform_youtube_processing
defaultLocation: europe-west2
defaultAssertionDataset: dataform_youtube_processing_assertions
dataformCoreVersion: 3.0.42


