
-- A table that contains the yearly output for engagement and content rpport data
config {
  type: "view",
  columns: {
    video_id: "video id identifier",
    month: "The month the data covers ",
    sharingService: "The video sharing service",
    shares: "The number of times a video has been shared"
  }
}

SELECT 
    video_id,
    month.
    sharingService,
    shares
FROM
 `gds-social-data.govuk_youtube_channel_staging.engagement_and_content_location`
